feat: update schema json files (and add files for Twitter)
community-tech-alliance/airbyte-source-sprout-social pull request #3
Opened 2023-12-23 17:15 UTC by emily-flambe

@kanelouise, this PR just makes some tweaks to the JSON schema files so that Airbyte syncs the data successfully into Airbyte. Seems to be working as intended in the latest image that I pushed (tag 0.0.2). Hooray!!

2024-01-03 17:56 UTC, kanelouise requested changes

2024-01-03 17:56 UTC, kanelouise commented on source_sprout_social/schemas/twitter_profile_analytics.json
> +  "properties": {
Thanks, @emily-flambe for the updating here! I'm curious about the omission of `perma_link` info from the `{social_media_site}_profile_analytics.json` files. Presently, the permalinks are being used as the primary keys.

2024-01-03 17:56 UTC, kanelouise commented on source_sprout_social/schemas/facebook_post_analytics.json
> +      "perma_link": {
I'm also curious about the underscore in `perma_link`. Was the previous spelling preventing something from happening correctly, or is the underscore preferred for some other reason? We'll just have to update the primary keys in source.py to match the spelling as well.

2024-01-03 18:59 UTC, kanelouise commented
The tables have turned in this PR! I updated the primary keys in `source.py`. Next step will be for me to push the image (will tag as 0.0.3) and test to make sure the things are running just fine still in dev.

2024-01-03 22:41 UTC, emily-flambe commented on source_sprout_social/schemas/twitter_profile_analytics.json
> +  "properties": {
ope! yeah my recollection is that I switched to perma_link instead of permalink because that was the field in the data... confusing tho, why do it gotta be like that

2024-01-03 22:42 UTC, emily-flambe commented on source_sprout_social/schemas/twitter_profile_analytics.json
> +  "properties": {
(Just to clarify, the "requested changes" are no longer needed here, right?)

2024-01-04 00:30 UTC, kanelouise commented on source_sprout_social/schemas/twitter_profile_analytics.json
> +  "properties": {
yep we're all square!

2024-01-04 01:01 UTC, kanelouise approved these changes

2024-01-04 01:23 UTC, merged